name: CI
permissions:
  checks: write
on:
  pull_request:
   types: [opened, synchronize, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'v2/go.mod'
    - name: generate
      run: make generate
    - name: lint
      run: make lint
    - name: test
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make test
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '.output/junit*.xml'
